version: '3.8'
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  inngest:
    build:
      context: .
      dockerfile: Dockerfile.inngest
    depends_on:
      - next
    env_file:
      - .env
    environment:
      - INNGEST_URL=http://next:3000/api/inngest
    # keep entrypoint default (runs npx inngest dev)
